name: Натравить clang-tidy на файлы проекта

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  run_clang_tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Запустить clang-tidy
        run: nix develop -c 'ls -la'
